version: '3.6'

services:
  bot:
    image: pwnker/jackbot:latest
    depends_on:
      - db
    environment:
      PGUSER: bot
      PGPASSWORD: 
      PGDATABASE: bot
      PGHOST: db
      TOKEN: 
      SHORT_API_KEY: 
      CLIENT_ID: 936735120906412113
      GUILD_ID: 
      BOT_LOG_CHANNEL:
    networks:
      - default
    restart: always

  db:
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: 
      POSTGRES_DB: bot
    image: postgres:latest
    networks:
      - default
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 --label-enable --cleanup