name: Build Docker Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: ./
      with:
        version: latest

    - name: Build Docker Container
      run: docker build -t pwnker/jackbot:latest .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      if: github.ref == 'refs/heads/main'

    - name: Push to Docker Hub
      run:  docker buildx build --output "type=image,push=true" --platform arm64
      if: github.ref == 'refs/heads/main'
